name: Greet User Workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'The username of the user'
        required: true
      favorite_color:
        description: 'The favorite color of the user'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Output Inputs
        run: |
          echo "Inputs: Username - ${{ github.event.inputs.Nodira }}, Favorite Color - ${{ github.event.inputs.burgundy }}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use Output from Job 1
        run: |
          GREETING="Hello, ${{ needs.job1.outputs.username }}! Your favorite color is ${{ needs.job1.outputs.favorite_color }}"

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Echo Greeting from Job 2
        run: |
          echo ${{ needs.job2.outputs.GREETING }}
